/**
 * The 61 Masters — complete persona database.
 * Each master maps to a pipeline group and carries their methodology,
 * signature move, and AI agent persona seed.
 */

export type PipelineGroup =
  | 'trend'
  | 'cycle'
  | 'value'
  | 'growth'
  | 'debate'
  | 'timing'
  | 'exit'
  | 'quant';

export interface Master {
  id: number;
  slug: string;
  nameEn: string;
  nameCn: string;
  group: PipelineGroup;
  groupLabel: string;
  role: string;
  methodology: string;
  signature: string;
  quote: string;
  era: string;
  avatarColor: string;
}

export const GROUP_META: Record<
  PipelineGroup,
  { label: string; labelCn: string; step: number; color: string; description: string }
> = {
  trend: {
    label: 'Trend Research',
    labelCn: '趋势研究组',
    step: 1,
    color: '#7c3aed',
    description: 'Where does capital flow over the next decade?',
  },
  cycle: {
    label: 'Cycle Research',
    labelCn: '周期研究组',
    step: 2,
    color: '#0891b2',
    description: 'Where are we in the cycle?',
  },
  value: {
    label: 'Value / Quality Selection',
    labelCn: '价值/质量选股',
    step: 3,
    color: '#059669',
    description: 'What to buy — margin of safety, moats, compounding machines',
  },
  growth: {
    label: 'Growth / Opportunity Selection',
    labelCn: '成长/机会选股',
    step: 3,
    color: '#d97706',
    description: 'What to buy — ten-baggers, catalysts, special situations',
  },
  debate: {
    label: 'Debate Layer',
    labelCn: '辩论层',
    step: 4,
    color: '#dc2626',
    description: 'Bull case vs. red-team interrogation — the soul of the product',
  },
  timing: {
    label: 'Timing',
    labelCn: '择时组',
    step: 5,
    color: '#2563eb',
    description: 'When to buy, and how much',
  },
  exit: {
    label: 'Exit Discipline',
    labelCn: '卖出组',
    step: 6,
    color: '#64748b',
    description: 'When to sell — including Bogle index accountability',
  },
  quant: {
    label: 'Quant Risk Control',
    labelCn: '量化风控层',
    step: 0,
    color: '#0d9488',
    description: 'Always on: verify every intuition',
  },
};

export const MASTERS: Master[] = [
  // ── Step 1: Trend Research (7) ──────────────────────────────
  {
    id: 1, slug: 'cathie-wood', nameEn: 'Cathie Wood', nameCn: '凯瑟琳·伍德',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Disruptive Innovation Lead',
    methodology: 'ARK-style thematic research across AI, robotics, genomics, blockchain, and energy storage.',
    signature: 'Identifies exponential adoption curves before consensus.',
    quote: 'The biggest risk is not taking enough risk on innovation.',
    era: 'Contemporary', avatarColor: '#7c3aed',
  },
  {
    id: 2, slug: 'philippe-laffont', nameEn: 'Philippe Laffont', nameCn: '菲利普·拉丰',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Tech Commercialization Validator',
    methodology: 'Coatue founder. Maps technology trends to commercialization inflection points.',
    signature: 'Validates which trends have crossed the chasm to revenue.',
    quote: 'Great trends need great business models.',
    era: 'Contemporary', avatarColor: '#6d28d9',
  },
  {
    id: 3, slug: 'chase-coleman', nameEn: 'Chase Coleman', nameCn: '蔡斯·科尔曼',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Internet & Consumer Penetration Tracker',
    methodology: 'Tiger Global. Tracks internet and new-consumer penetration rates globally.',
    signature: 'Early-stage growth investing in category-defining companies.',
    quote: 'The best investments look obvious in hindsight.',
    era: 'Contemporary', avatarColor: '#5b21b6',
  },
  {
    id: 4, slug: 'ron-baron', nameEn: 'Ron Baron', nameCn: '罗恩·巴伦',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Decade-Long Growth Scout',
    methodology: 'Baron Funds. Identifies companies that can compound for 10+ years.',
    signature: 'Early Tesla backer; holds through volatility for multi-decade compounding.',
    quote: 'I invest in people, not just companies.',
    era: 'Contemporary', avatarColor: '#4c1d95',
  },
  {
    id: 5, slug: 't-rowe-price', nameEn: 'T. Rowe Price', nameCn: 'T. Rowe 普莱斯',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Historical Growth Cycle Analyst',
    methodology: 'Founder of growth stock investing philosophy. Historical analogy to current cycles.',
    signature: 'Pioneered the growth stock approach in the 1930s–60s.',
    quote: 'Change is the investor\'s only certainty.',
    era: 'Historical', avatarColor: '#7c3aed',
  },
  {
    id: 6, slug: 'ken-fisher', nameEn: 'Ken Fisher', nameCn: '肯·费雪',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Global Capital Flow Analyst',
    methodology: 'Fisher Investments. PSR ratio inventor. Global fund flow and valuation divergence.',
    signature: 'Son of Philip Fisher; quantifies sentiment-driven mispricings.',
    quote: 'The market is a great humiliator.',
    era: 'Contemporary', avatarColor: '#8b5cf6',
  },
  {
    id: 7, slug: 'mark-mobius', nameEn: 'Mark Mobius', nameCn: '马克·墨比尔斯',
    group: 'trend', groupLabel: 'Trend Research',
    role: 'Emerging Markets Perspective',
    methodology: 'Templeton Emerging Markets. Geopolitical diffusion path of global trends.',
    signature: 'The godfather of emerging market investing.',
    quote: 'The best opportunities are where others fear to tread.',
    era: 'Contemporary', avatarColor: '#a78bfa',
  },

  // ── Step 2: Cycle Research (9) ──────────────────────────────
  {
    id: 8, slug: 'ray-dalio', nameEn: 'Ray Dalio', nameCn: '瑞·达利欧',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Debt Cycle Architect',
    methodology: 'Bridgewater. Long-term and short-term debt cycle positioning (Bridgewater paradigm).',
    signature: 'All-weather strategy; principles-based radical transparency.',
    quote: 'He who lives by the crystal ball will eat shattered glass.',
    era: 'Contemporary', avatarColor: '#0891b2',
  },
  {
    id: 9, slug: 'howard-marks', nameEn: 'Howard Marks', nameCn: '霍华德·马克斯',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Market Pendulum Assessor',
    methodology: 'Oaktree Capital. Second-level thinking; market pendulum position evaluation.',
    signature: 'Investment memos are required reading on Wall Street.',
    quote: 'The most important thing is being attentive to cycles.',
    era: 'Contemporary', avatarColor: '#0e7490',
  },
  {
    id: 10, slug: 'john-templeton', nameEn: 'John Templeton', nameCn: '约翰·邓普顿',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Sentiment Extremes Detector',
    methodology: 'Global diversification pioneer. Maximum pessimism = optimal buying point.',
    signature: 'Bought every stock trading below $1 at the start of WWII.',
    quote: 'The time of maximum pessimism is the best time to buy.',
    era: 'Historical', avatarColor: '#155e75',
  },
  {
    id: 11, slug: 'george-soros', nameEn: 'George Soros', nameCn: '乔治·索罗斯',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Reflexivity Tester',
    methodology: 'Reflexivity theory: is the trend self-reinforcing or self-destroying?',
    signature: 'Broke the Bank of England in 1992.',
    quote: 'It\'s not whether you\'re right or wrong, but how much you make when you\'re right.',
    era: 'Contemporary', avatarColor: '#164e63',
  },
  {
    id: 12, slug: 'john-maynard-keynes', nameEn: 'John Maynard Keynes', nameCn: '凯恩斯',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Consensus Beauty Contest Analyst',
    methodology: 'What consensus is the market pricing? Where is the consensus wrong?',
    signature: 'Managed King\'s College Cambridge fund to ~12% annualized.',
    quote: 'The market can stay irrational longer than you can stay solvent.',
    era: 'Historical', avatarColor: '#0c4a6e',
  },
  {
    id: 13, slug: 'alan-howard', nameEn: 'Alan Howard', nameCn: '艾伦·霍华德',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Rates & Liquidity Cycle Judge',
    methodology: 'Brevan Howard. Global macro bond cycle and liquidity assessment.',
    signature: 'One of the most successful macro traders of his generation.',
    quote: 'Liquidity is the only thing that matters in a crisis.',
    era: 'Contemporary', avatarColor: '#075985',
  },
  {
    id: 14, slug: 'bill-gross', nameEn: 'Bill Gross', nameCn: '比尔·格罗斯',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Bond Market Signal Reader',
    methodology: 'PIMCO Total Return. Yield curve and credit spread interpretation.',
    signature: 'The Bond King; decoded bond market signals for equity investors.',
    quote: 'Bonds are the smarter market.',
    era: 'Contemporary', avatarColor: '#0369a1',
  },
  {
    id: 15, slug: 'john-paulson', nameEn: 'John Paulson', nameCn: '约翰·保尔森',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Credit Quality & Systemic Risk Monitor',
    methodology: 'Paulson & Co. Credit quality and systemic risk monitoring.',
    signature: 'Made ~$20B shorting subprime in 2007–2008.',
    quote: 'The greatest trade ever.',
    era: 'Contemporary', avatarColor: '#0284c7',
  },
  {
    id: 16, slug: 'paul-tudor-jones', nameEn: 'Paul Tudor Jones', nameCn: '保罗·都铎·琼斯',
    group: 'cycle', groupLabel: 'Cycle Research',
    role: 'Macro Cycle Inflection Confirmer',
    methodology: 'Tudor Investment. Macro trading perspective on cycle turning points.',
    signature: 'Profited 62% in the month of the 1987 crash.',
    quote: 'The most important rule of trading is to play great defense.',
    era: 'Contemporary', avatarColor: '#0ea5e9',
  },

  // ── Step 3A: Value / Quality Selection (10) ─────────────────
  {
    id: 17, slug: 'benjamin-graham', nameEn: 'Benjamin Graham', nameCn: '本杰明·格雷厄姆',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Margin of Safety Guardian',
    methodology: 'Price < 2/3 of intrinsic value. The father of value investing.',
    signature: 'Wrote Security Analysis and The Intelligent Investor.',
    quote: 'The investor\'s chief problem — and even his worst enemy — is likely to be himself.',
    era: 'Historical', avatarColor: '#059669',
  },
  {
    id: 18, slug: 'warren-buffett', nameEn: 'Warren Buffett', nameCn: '沃伦·巴菲特',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Moat & Management Final Review',
    methodology: 'Berkshire Hathaway. Moat + ROE + management quality. 60-year ~20% annualized.',
    signature: 'The Oracle of Omaha; compound interest personified.',
    quote: 'Our favorite holding period is forever.',
    era: 'Contemporary', avatarColor: '#047857',
  },
  {
    id: 19, slug: 'walter-schloss', nameEn: 'Walter Schloss', nameCn: '沃尔特·施洛斯',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Cigar Butt Specialist',
    methodology: 'PB < 0.8, low debt, diversified holdings. 47-year ~15.3% annualized.',
    signature: 'Graham\'s disciple; never attended college, outperformed most MBAs.',
    quote: 'I don\'t like stress. I buy cheap stocks.',
    era: 'Historical', avatarColor: '#065f46',
  },
  {
    id: 20, slug: 'john-neff', nameEn: 'John Neff', nameCn: '约翰·聂夫',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Low P/E + Growth-Adjusted Screener',
    methodology: 'Windsor Fund. Low P/E with growth adjustment (original GARP). 31 years beating the market.',
    signature: 'Turned Windsor Fund into a powerhouse through disciplined value.',
    quote: 'It\'s not always easy to do what\'s not popular.',
    era: 'Historical', avatarColor: '#064e3b',
  },
  {
    id: 21, slug: 'seth-klarman', nameEn: 'Seth Klarman', nameCn: '赛斯·卡拉曼',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Distressed & Special Situations',
    methodology: 'Baupost Group. Deep value + cash patience. Author of Margin of Safety.',
    signature: 'His out-of-print book sells for thousands of dollars.',
    quote: 'The single greatest edge an investor can have is a long-term orientation.',
    era: 'Contemporary', avatarColor: '#052e16',
  },
  {
    id: 22, slug: 'chuck-akre', nameEn: 'Chuck Akre', nameCn: '查克·阿克雷',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Compounding Machine Identifier',
    methodology: 'Three-legged stool: business model / reinvestment / management. ~13%+ compounded.',
    signature: 'Akre Focus Fund; identifies businesses that compound relentlessly.',
    quote: 'We\'re looking for compounding machines.',
    era: 'Contemporary', avatarColor: '#059669',
  },
  {
    id: 23, slug: 'terry-smith', nameEn: 'Terry Smith', nameCn: '特里·史密斯',
    group: 'value', groupLabel: 'Value Selection',
    role: 'High ROCE + Buy-and-Hold Candidate',
    methodology: 'Fundsmith. Buy good companies, don\'t overpay, do nothing.',
    signature: 'The English Warren Buffett; ultra-low turnover.',
    quote: 'Buy good companies. Don\'t overpay. Do nothing.',
    era: 'Contemporary', avatarColor: '#10b981',
  },
  {
    id: 24, slug: 'hetty-green', nameEn: 'Hetty Green', nameCn: '海蒂·格林',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Extreme Cheapness + Balance Sheet Purist',
    methodology: 'The Witch of Wall Street. Extreme cheapness + impeccable balance sheets.',
    signature: 'First woman to amass a fortune through investing in America.',
    quote: 'Buy cheap, sell dear, act with thrift and shrewdness.',
    era: 'Historical', avatarColor: '#34d399',
  },
  {
    id: 25, slug: 'duan-yongping', nameEn: 'Duan Yongping', nameCn: '段永平',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Business Model Clarity Checker',
    methodology: '"Buying a stock is buying a company." Heavy Apple/Moutai positions.',
    signature: 'Chinese value investing spiritual leader.',
    quote: 'If you don\'t understand the business, don\'t buy the stock.',
    era: 'Contemporary', avatarColor: '#6ee7b7',
  },
  {
    id: 26, slug: 'li-lu', nameEn: 'Li Lu', nameCn: '李录',
    group: 'value', groupLabel: 'Value Selection',
    role: 'Circle of Competence + Civilization Cycle',
    methodology: 'Himalaya Capital. Munger family asset manager. Chinese assets expert.',
    signature: 'Author of Civilization, Modernization, Value Investing and China.',
    quote: 'Value investing is about understanding the true nature of business.',
    era: 'Contemporary', avatarColor: '#a7f3d0',
  },

  // ── Step 3B: Growth / Opportunity Selection (10) ────────────
  {
    id: 27, slug: 'peter-lynch', nameEn: 'Peter Lynch', nameCn: '彼得·林奇',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Ten-Bagger Hunter',
    methodology: 'Magellan Fund. 13-year ~29% annualized. Invest in what you know.',
    signature: 'Six-category company classification system.',
    quote: 'Know what you own, and know why you own it.',
    era: 'Contemporary', avatarColor: '#d97706',
  },
  {
    id: 28, slug: 'bill-miller', nameEn: 'Bill Miller', nameCn: '比尔·米勒',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Contrarian Growth Identifier',
    methodology: 'Legg Mason. 15 consecutive years beating S&P 500 (1991–2005).',
    signature: 'Buys high-competitive companies temporarily out of favor.',
    quote: 'The market\'s perception and reality often diverge.',
    era: 'Contemporary', avatarColor: '#b45309',
  },
  {
    id: 29, slug: 'julian-robertson', nameEn: 'Julian Robertson', nameCn: '朱利安·罗伯逊',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Global Long/Short Pairing',
    methodology: 'Tiger Management. Global best long/short pair selection.',
    signature: 'The godfather of hedge funds; spawned the Tiger Cubs.',
    quote: 'The best way to manage money is to be long the best and short the worst.',
    era: 'Historical', avatarColor: '#92400e',
  },
  {
    id: 30, slug: 'andreas-halvorsen', nameEn: 'Andreas Halvorsen', nameCn: '安德烈亚斯·哈尔沃森',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Large-Cap Growth + Industry Leader',
    methodology: 'Viking Global. Large-cap growth and industry leader portfolios.',
    signature: 'Largest Tiger Cub successor fund.',
    quote: 'We look for businesses with durable competitive advantages.',
    era: 'Contemporary', avatarColor: '#78350f',
  },
  {
    id: 31, slug: 'stephen-mandel', nameEn: 'Stephen Mandel', nameCn: '斯蒂芬·曼德尔',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Growth-Value Cross-Validator',
    methodology: 'Lone Pine. Growth and value dual-factor cross-validation.',
    signature: 'One of the most consistent Tiger Cub performers.',
    quote: 'The best investments combine growth with reasonable valuation.',
    era: 'Contemporary', avatarColor: '#451a03',
  },
  {
    id: 32, slug: 'lee-ainslie', nameEn: 'Lee Ainslie', nameCn: '李·安斯利',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Tech/Services Deep Fundamental',
    methodology: 'Maverick Capital. Deep fundamental analysis in tech and services sectors.',
    signature: 'Tiger Cub evergreen; consistent performer across cycles.',
    quote: 'Deep research is the only sustainable edge.',
    era: 'Contemporary', avatarColor: '#d97706',
  },
  {
    id: 33, slug: 'bill-ackman', nameEn: 'Bill Ackman', nameCn: '比尔·阿克曼',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Quality Giant + Activist Catalyst',
    methodology: 'Pershing Square. Quality giants + activist value-release catalysts.',
    signature: 'Made $2.6B shorting COVID in 2020; famous Herbalife battle with Icahn.',
    quote: 'I\'m not emotional about investments. I\'m emotional about being right.',
    era: 'Contemporary', avatarColor: '#f59e0b',
  },
  {
    id: 34, slug: 'david-tepper', nameEn: 'David Tepper', nameCn: '大卫·泰珀',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Distressed Reversal & Crisis Bottom-Fisher',
    methodology: 'Appaloosa Management. Distressed reversal and crisis bottom-fishing.',
    signature: 'Doubled his fund in 2009 by buying bank stocks at the bottom.',
    quote: 'The key is to be greedy when others are fearful.',
    era: 'Contemporary', avatarColor: '#fbbf24',
  },
  {
    id: 35, slug: 'mohnish-pabrai', nameEn: 'Mohnish Pabrai', nameCn: '莫尼什·帕伯莱',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Formulaic Buffett Cloner',
    methodology: 'Pabrai Funds. "Shameless cloning" of Buffett. Low-fee, high-concentration.',
    signature: 'Paid $650K for a charity lunch with Buffett; considers it the best investment ever.',
    quote: 'I\'m a shameless cloner.',
    era: 'Contemporary', avatarColor: '#fcd34d',
  },
  {
    id: 36, slug: 'joel-greenblatt', nameEn: 'Joel Greenblatt', nameCn: '乔尔·格林布拉特',
    group: 'growth', groupLabel: 'Growth Selection',
    role: 'Magic Formula + Special Situations',
    methodology: 'Gotham Capital. Magic Formula ranking + special situation arbitrage.',
    signature: 'Author of The Little Book That Beats the Market.',
    quote: 'The secret to investing is to figure out the value of something and pay less.',
    era: 'Contemporary', avatarColor: '#fde68a',
  },

  // ── Step 4: Debate Layer (8) ────────────────────────────────
  {
    id: 37, slug: 'david-einhorn', nameEn: 'David Einhorn', nameCn: '大卫·艾因霍恩',
    group: 'debate', groupLabel: 'Debate Layer — Red Team',
    role: 'Financial Statement Quality Inquisitor',
    methodology: 'Greenlight Capital. Forensic accounting and earnings quality interrogation.',
    signature: 'Famous for shorting Lehman Brothers before its collapse.',
    quote: 'We look for situations where the market is wrong about a company\'s fundamentals.',
    era: 'Contemporary', avatarColor: '#dc2626',
  },
  {
    id: 38, slug: 'michael-burry', nameEn: 'Michael Burry', nameCn: '迈克尔·伯里',
    group: 'debate', groupLabel: 'Debate Layer — Red Team',
    role: 'Extreme Contrarian: Hidden Assumptions',
    methodology: 'Scion Capital. What assumptions are buried in the valuation model?',
    signature: 'The Big Short prototype; reads financial statements like novels.',
    quote: 'I don\'t care what the market thinks. I care what the numbers say.',
    era: 'Contemporary', avatarColor: '#b91c1c',
  },
  {
    id: 39, slug: 'carl-icahn', nameEn: 'Carl Icahn', nameCn: '卡尔·伊坎',
    group: 'debate', groupLabel: 'Debate Layer — Red Team',
    role: 'Governance & Self-Dealing Interrogator',
    methodology: 'Icahn Enterprises. Corporate governance and self-dealing scrutiny.',
    signature: 'The original activist investor; the "Icahn Lift" is a real market phenomenon.',
    quote: 'Some people get rich studying artificial intelligence. Me, I make money studying natural stupidity.',
    era: 'Contemporary', avatarColor: '#991b1b',
  },
  {
    id: 40, slug: 'dan-loeb', nameEn: 'Dan Loeb', nameCn: '丹·勒布',
    group: 'debate', groupLabel: 'Debate Layer — Red Team',
    role: 'Narrative & Catalyst Authenticity Checker',
    methodology: 'Third Point. Sharp shareholder letters + event-driven analysis.',
    signature: 'Known for scathing letters to underperforming management teams.',
    quote: 'We are not afraid to be contrarian when the facts support it.',
    era: 'Contemporary', avatarColor: '#7f1d1d',
  },
  {
    id: 41, slug: 'paul-singer', nameEn: 'Paul Singer', nameCn: '保罗·辛格',
    group: 'debate', groupLabel: 'Debate Layer — Red Team',
    role: 'Tail Risk & Legal/Contract Vulnerability',
    methodology: 'Elliott Management. Activist and distressed debt. Tail risk and legal vulnerability.',
    signature: 'Famous for battling Argentina over sovereign debt for 15 years — and winning.',
    quote: 'The most dangerous words in investing: this time is different.',
    era: 'Contemporary', avatarColor: '#450a0a',
  },
  {
    id: 42, slug: 'michael-steinhardt', nameEn: 'Michael Steinhardt', nameCn: '迈克尔·斯坦哈特',
    group: 'debate', groupLabel: 'Debate Layer — Variant View',
    role: 'Consensus Divergence Tester',
    methodology: 'Hedge fund pioneer. 30-year ~24% annualized. Where does this thesis diverge from consensus?',
    signature: 'One of the first true hedge fund managers.',
    quote: 'The markets are always changing, and so must you.',
    era: 'Contemporary', avatarColor: '#ef4444',
  },
  {
    id: 43, slug: 'stanley-druckenmiller', nameEn: 'Stanley Druckenmiller', nameCn: '斯坦利·德鲁肯米勒',
    group: 'debate', groupLabel: 'Debate Layer — Pressure Test',
    role: 'Conviction Concentration Stress Test',
    methodology: 'Duquesne Capital. 30+ year ~30% annualized. "If you had one shot, would you bet big?"',
    signature: 'Soros\'s top lieutenant; never had a losing year.',
    quote: 'It takes courage to be a pig.',
    era: 'Contemporary', avatarColor: '#f87171',
  },
  {
    id: 44, slug: 'charlie-munger', nameEn: 'Charlie Munger', nameCn: '查理·芒格',
    group: 'debate', groupLabel: 'Debate Layer — Chairman',
    role: 'Inversion Thinking Arbiter',
    methodology: 'Berkshire Hathaway. Multi-disciplinary mental models. "How would I kill this thesis?"',
    signature: 'Buffett\'s chief thought partner; the architect of Berkshire\'s culture.',
    quote: 'Invert, always invert.',
    era: 'Historical', avatarColor: '#fca5a5',
  },

  // ── Step 5: Timing (5) ──────────────────────────────────────
  {
    id: 45, slug: 'william-oneil', nameEn: 'William O\'Neil', nameCn: '威廉·欧奈尔',
    group: 'timing', groupLabel: 'Timing',
    role: 'CANSLIM Entry Point',
    methodology: 'CANSLIM system. Cup-with-handle breakout + market follow-through indicator.',
    signature: 'Founded Investor\'s Business Daily; studied every big winner since 1880.',
    quote: 'The whole secret to winning in the stock market is to lose the least amount possible.',
    era: 'Historical', avatarColor: '#2563eb',
  },
  {
    id: 46, slug: 'mark-minervini', nameEn: 'Mark Minervini', nameCn: '马克·米勒维尼',
    group: 'timing', groupLabel: 'Timing',
    role: 'SEPA Stage-2 Confirmation',
    methodology: 'SEPA system. Stage-2 uptrend confirmation for precise entry timing.',
    signature: 'US Investing Championship winner with 155% annualized return.',
    quote: 'Risk management is the key to survival.',
    era: 'Contemporary', avatarColor: '#1d4ed8',
  },
  {
    id: 47, slug: 'richard-dennis', nameEn: 'Richard Dennis', nameCn: '理查德·丹尼斯',
    group: 'timing', groupLabel: 'Timing',
    role: 'Turtle Breakout System',
    methodology: 'Turtle Trading. 20-day/55-day breakout system for systematic entries.',
    signature: 'Proved trading can be taught through the Turtle experiment.',
    quote: 'I always say you could publish my trading rules in the newspaper and no one would follow them.',
    era: 'Historical', avatarColor: '#1e40af',
  },
  {
    id: 48, slug: 'ed-seykota', nameEn: 'Ed Seykota', nameCn: '艾德·斯科塔',
    group: 'timing', groupLabel: 'Timing',
    role: 'Trend-Following Momentum Confirmer',
    methodology: 'Trend-following pioneer. Price momentum direction confirmation.',
    signature: '16-year account growth of 250,000x (with compounding).',
    quote: 'Ride your winners, cut your losses, manage your risk.',
    era: 'Contemporary', avatarColor: '#1e3a8a',
  },
  {
    id: 49, slug: 'steve-cohen', nameEn: 'Steve Cohen', nameCn: '史蒂夫·科恩',
    group: 'timing', groupLabel: 'Timing',
    role: 'Short-Term Signal & Tape Reading',
    methodology: 'Point72/SAC. Anomaly detection, volume-price action, news reaction.',
    signature: 'Arguably the greatest short-term trader in history.',
    quote: 'The best traders have no ego.',
    era: 'Contemporary', avatarColor: '#172554',
  },

  // ── Step 6: Exit Discipline (5) ─────────────────────────────
  {
    id: 50, slug: 'jesse-livermore', nameEn: 'Jesse Livermore', nameCn: '杰西·利弗莫尔',
    group: 'exit', groupLabel: 'Exit Discipline',
    role: 'Stop-Loss Iron Rule + Let Profits Run',
    methodology: 'The Boy Plunger. Stop-loss discipline + letting profits run.',
    signature: 'Made $100M shorting the 1929 crash.',
    quote: 'It never was my thinking that made the big money for me. It always was my sitting.',
    era: 'Historical', avatarColor: '#64748b',
  },
  {
    id: 51, slug: 'bernard-baruch', nameEn: 'Bernard Baruch', nameCn: '伯纳德·巴鲁克',
    group: 'exit', groupLabel: 'Exit Discipline',
    role: 'Early Exit Optimist',
    methodology: '"I always sold too soon." — The optimistic early-exit approach.',
    signature: 'Advised multiple US presidents; the "shoeshine boy" indicator.',
    quote: 'I made my money by selling too soon.',
    era: 'Historical', avatarColor: '#475569',
  },
  {
    id: 52, slug: 'nicolas-darvas', nameEn: 'Nicolas Darvas', nameCn: '尼古拉斯·达瓦斯',
    group: 'exit', groupLabel: 'Exit Discipline',
    role: 'Box Theory Trailing Stop',
    methodology: 'Darvas Box Theory. Sell when the box breaks — the original trailing stop.',
    signature: 'A dancer who turned $25K into $2M in 2 years.',
    quote: 'I never bought a stock unless it was making a new high.',
    era: 'Historical', avatarColor: '#334155',
  },
  {
    id: 53, slug: 'philip-fisher', nameEn: 'Philip Fisher', nameCn: '菲利普·费雪',
    group: 'exit', groupLabel: 'Exit Discipline',
    role: 'Anti-Overtrading Supervisor',
    methodology: 'Common Stocks and Uncommon Profits. Only sell on mistake or fundamental deterioration.',
    signature: 'The "scuttlebutt" method; father of growth investing.',
    quote: 'The stock market is filled with individuals who know the price of everything but the value of nothing.',
    era: 'Historical', avatarColor: '#1e293b',
  },
  {
    id: 54, slug: 'john-bogle', nameEn: 'John Bogle', nameCn: '约翰·博格',
    group: 'exit', groupLabel: 'Exit Discipline',
    role: 'Index Fund Accountability Backstop',
    methodology: 'Vanguard. If the committee can\'t beat the index, switch everything to index funds.',
    signature: 'The father of index investing; benefactor of millions of ordinary investors.',
    quote: 'Don\'t look for the needle in the haystack. Just buy the haystack.',
    era: 'Historical', avatarColor: '#0f172a',
  },

  // ── Quant Risk Control (7) ──────────────────────────────────
  {
    id: 55, slug: 'ed-thorp', nameEn: 'Ed Thorp', nameCn: '爱德华·索普',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Kelly Criterion Position Sizing',
    methodology: 'Quantitative investing pioneer. Blackjack card counting → market beating. Kelly formula.',
    signature: 'Wrote Beat the Dealer and Beat the Market.',
    quote: 'The Kelly criterion tells you exactly how much to bet.',
    era: 'Contemporary', avatarColor: '#0d9488',
  },
  {
    id: 56, slug: 'jim-simons', nameEn: 'Jim Simons', nameCn: '吉姆·西蒙斯',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Statistical Significance Validator',
    methodology: 'Renaissance Technologies. Medallion Fund ~66% annualized (pre-fee). Signal significance testing.',
    signature: 'The Quant King; mathematician who cracked the market code.',
    quote: 'We don\'t override the models.',
    era: 'Contemporary', avatarColor: '#0f766e',
  },
  {
    id: 57, slug: 'ken-griffin', nameEn: 'Ken Griffin', nameCn: '肯·格里芬',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Multi-Strategy Integration & Execution Cost',
    methodology: 'Citadel. Multi-strategy platform. Execution cost control and integration.',
    signature: 'Built the most profitable hedge fund in history.',
    quote: 'We are in the business of managing risk, not avoiding it.',
    era: 'Contemporary', avatarColor: '#115e59',
  },
  {
    id: 58, slug: 'david-shaw', nameEn: 'David E. Shaw', nameCn: '大卫·肖',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Model Pipeline Architecture',
    methodology: 'D.E. Shaw. Computational finance pioneer. Methodology engineering.',
    signature: 'Turned computer science into a hedge fund empire.',
    quote: 'The intersection of computer science and finance is where the magic happens.',
    era: 'Contemporary', avatarColor: '#134e4a',
  },
  {
    id: 59, slug: 'cliff-asness', nameEn: 'Cliff Asness', nameCn: '克里夫·阿斯内斯',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Factor Exposure Analysis',
    methodology: 'AQR Capital. Factor investing academic. Is the portfolio skill or style exposure?',
    signature: 'Bridges academic finance and practical investing.',
    quote: 'Value and momentum are the two most robust factors in investing.',
    era: 'Contemporary', avatarColor: '#042f2e',
  },
  {
    id: 60, slug: 'two-sigma', nameEn: 'Overdeck & Siegel', nameCn: 'Two Sigma 创始人',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Alternative Data Cross-Validation',
    methodology: 'Two Sigma. Data science-driven. Alternative data cross-validation.',
    signature: 'Pioneered the use of machine learning and alternative data in investing.',
    quote: 'Data science is the future of investment management.',
    era: 'Contemporary', avatarColor: '#14b8a6',
  },
  {
    id: 61, slug: 'israel-englander', nameEn: 'Israel Englander', nameCn: '伊斯雷尔·英格兰德',
    group: 'quant', groupLabel: 'Quant Risk Control',
    role: 'Platform Risk: Single-View Loss Cap',
    methodology: 'Millennium Management. 160+ investment teams. Any single view has a loss limit.',
    signature: 'Built the ultimate multi-manager platform.',
    quote: 'Risk management is not a department. It\'s a culture.',
    era: 'Contemporary', avatarColor: '#2dd4bf',
  },
];

export const getMastersByGroup = (group: PipelineGroup) =>
  MASTERS.filter((m) => m.group === group);

export const getMasterBySlug = (slug: string) =>
  MASTERS.find((m) => m.slug === slug);

export const GROUP_ORDER: PipelineGroup[] = [
  'trend',
  'cycle',
  'value',
  'growth',
  'debate',
  'timing',
  'exit',
  'quant',
];

export { PIPELINE_STEPS } from './pipeline';
